baseurl: 
title : ImF2e
description: I'm Front End Engineer
paginate: 15

#导航
navs :
  - text : Index
    url  : /
  - text : Snippets
    url  : /snippets.html
  - text : Plugins
    url  : /plugins.html
